### ISSUE TITLE
ClippingBezier framework not found

### ISSUE THREAD

**Issue by genericptr** [prasad1120/ElegantPopover#2]
Trying to build after installing with CocoaPods I get the error `ld: framework not found ClippingBezier`. I'm not sure if this is a bug or I am required to complete more steps to install the dependancies (I'm new to CocoaPods).

My output during "pod install":

$ pod init
$ pod install
Analyzing dependencies
Downloading dependencies
Installing ClippingBezier (1.0.6)
Installing ElegantPopover (1.0.0)
Installing PerformanceBezier (1.0.34)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `***.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.

[!] Automatically assigning platform `iOS` with version `11.0` on target `***` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

**Comment by prasad1120** [comment]
After you installed the pods, did you open `**.xcworkspace` file instead of `**.xcodeproj` and then tried building the project?
